apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: frontend-service
  namespace: demo-app
spec:
  ingressClassName: nginx
  rules:
  - host: "demoapp.edr.cloudns.be"
    http:
      paths:
      - backend:
          service:
            name: frontend-service
            port:
              number: 4000
        path: /
        pathType: Prefix